require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'config/initializers/secret_token.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.pryrc'
  DisplayCopNames: true
  DisplayStyleGuide: true.
  NewCops: enable

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Rails/FilePath:
  EnforcedStyle: arguments

Metrics/BlockLength:
  Exclude:
    - '**/Guardfile'
    - '**/*.rake'
    - 'config/environments/*'
    - 'config/routes.rb'
    - 'spec/**/*'

Layout/LineLength:
  Max: 140

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Rails/HttpPositionalArguments:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/v1/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Enable cops that are disabled by default, but are useful nonetheless
# See https://github.com/bbatsov/rubocop/blob/master/config/disabled.yml

Rails:
  Enabled: true

RSpec/LeadingSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: False

Style/AutoResourceCleanup:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringMethods:
  Enabled: true

Naming/MemoizedInstanceVariableName:
  Enabled: false

RSpec/FilePath:
  Enabled: false
